"""add_chats_messages_reads

Revision ID: 322490a2446b
Revises: 149cae0658e6
Create Date: 2026-04-11 22:08:05.491266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '322490a2446b'
down_revision: Union[str, None] = '149cae0658e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_members', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('chat_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('chat_members_chat_id_user_id_key', 'chat_members', type_='unique')
    op.create_index(op.f('ix_chat_members_chat_id'), 'chat_members', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_members_user_id'), 'chat_members', ['user_id'], unique=False)
    op.drop_constraint('chat_members_user_id_fkey', 'chat_members', type_='foreignkey')
    op.drop_constraint('chat_members_chat_id_fkey', 'chat_members', type_='foreignkey')
    op.create_foreign_key(None, 'chat_members', 'chats', ['chat_id'], ['id'])
    op.create_foreign_key(None, 'chat_members', 'users', ['user_id'], ['id'])
    op.alter_column('chats', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('chats', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('message_reads', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_message_reads_user', table_name='message_reads')
    op.drop_constraint('message_reads_message_id_fkey', 'message_reads', type_='foreignkey')
    op.drop_constraint('message_reads_user_id_fkey', 'message_reads', type_='foreignkey')
    op.create_foreign_key(None, 'message_reads', 'messages', ['message_id'], ['id'])
    op.create_foreign_key(None, 'message_reads', 'users', ['user_id'], ['id'])
    op.alter_column('messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('messages', 'idempotency_key',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_messages_chat_created', table_name='messages')
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_column('messages', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.create_index('idx_messages_chat_created', 'messages', ['chat_id', 'created_at'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'idempotency_key',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'message_reads', type_='foreignkey')
    op.drop_constraint(None, 'message_reads', type_='foreignkey')
    op.create_foreign_key('message_reads_user_id_fkey', 'message_reads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('message_reads_message_id_fkey', 'message_reads', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_message_reads_user', 'message_reads', ['user_id', 'message_id'], unique=False)
    op.alter_column('message_reads', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chats', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('chats', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.create_foreign_key('chat_members_chat_id_fkey', 'chat_members', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('chat_members_user_id_fkey', 'chat_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_members_user_id'), table_name='chat_members')
    op.drop_index(op.f('ix_chat_members_chat_id'), table_name='chat_members')
    op.create_unique_constraint('chat_members_chat_id_user_id_key', 'chat_members', ['chat_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('chat_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_members', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###